import { groupByStateAndSortByCreatedAt } from '../../../../src/etls/breweries/transformations';

const data = [
  {
    id: 1,
    obdbId: 'bnaf-llc-austin',
    name: 'Bnaf, LLC',
    breweryType: 'planning',
    street: null,
    address2: null,
    address3: null,
    city: 'Austin',
    state: 'Texas',
    countyProvince: null,
    postalCode: '78727-7602',
    country: 'United States',
    longitude: null,
    latitude: null,
    phone: null,
    websiteUrl: null,
    updatedAt: '2018-07-24T00:00:00.000Z',
    createdAt: '2017-07-24T00:00:00.000Z',
  },
  {
    id: 2,
    obdbId: 'clermont-brewing-company-clermont',
    name: 'Clermont Brewing Company',
    breweryType: 'planning',
    street: null,
    address2: null,
    address3: null,
    city: 'Clermont',
    state: 'Florida',
    countyProvince: null,
    postalCode: '34711-2108',
    country: 'United States',
    longitude: '-83.254258',
    latitude: '30.133335',
    phone: null,
    websiteUrl: null,
    updatedAt: '2018-08-11T00:00:00.000Z',
    createdAt: '2018-07-24T00:00:00.000Z',
  },
  {
    id: 3,
    obdbId: 'king-fox-brewery-hialeah',
    name: 'King Fox Brewery',
    breweryType: 'planning',
    street: null,
    address2: null,
    address3: null,
    city: 'Hialeah',
    state: 'Florida',
    countyProvince: null,
    postalCode: '33014-5231',
    country: 'United States',
    longitude: '-81.399649',
    latitude: '27.153684',
    phone: null,
    websiteUrl: null,
    updatedAt: '2018-08-11T00:00:00.000Z',
    createdAt: '2020-07-24T00:00:00.000Z',
  },
];

const transformedData = {
  Texas: [
    {
      id: 1,
      obdbId: 'bnaf-llc-austin',
      name: 'Bnaf, LLC',
      breweryType: 'planning',
      street: null,
      address2: null,
      address3: null,
      city: 'Austin',
      state: 'Texas',
      countyProvince: null,
      postalCode: '78727-7602',
      country: 'United States',
      longitude: null,
      latitude: null,
      phone: null,
      websiteUrl: null,
      updatedAt: '2018-07-24T00:00:00.000Z',
      createdAt: '2017-07-24T00:00:00.000Z',
    },
  ],
  Florida: [
    {
      id: 3,
      obdbId: 'king-fox-brewery-hialeah',
      name: 'King Fox Brewery',
      breweryType: 'planning',
      street: null,
      address2: null,
      address3: null,
      city: 'Hialeah',
      state: 'Florida',
      countyProvince: null,
      postalCode: '33014-5231',
      country: 'United States',
      longitude: '-81.399649',
      latitude: '27.153684',
      phone: null,
      websiteUrl: null,
      updatedAt: '2018-08-11T00:00:00.000Z',
      createdAt: '2020-07-24T00:00:00.000Z',
    },
    {
      id: 2,
      obdbId: 'clermont-brewing-company-clermont',
      name: 'Clermont Brewing Company',
      breweryType: 'planning',
      street: null,
      address2: null,
      address3: null,
      city: 'Clermont',
      state: 'Florida',
      countyProvince: null,
      postalCode: '34711-2108',
      country: 'United States',
      longitude: '-83.254258',
      latitude: '30.133335',
      phone: null,
      websiteUrl: null,
      updatedAt: '2018-08-11T00:00:00.000Z',
      createdAt: '2018-07-24T00:00:00.000Z',
    },
  ],
};

describe('`groupByStateAndSortByCreatedAt` function', () => {
  test('should group by `state` and sort by `createdAt` in descending order', () => {
    expect(groupByStateAndSortByCreatedAt(data)).toEqual(transformedData);
  });
});
